#!/bin/bash
# Generate logpath for domlog-based jails, excluding users/domains from whitelist-domains.conf
# Output: writes /etc/fail2ban/jail.d/99-domlog-logpath.conf
# Run as root. Called by update.sh.

set -e

CONFIG="/etc/fail2ban/conf.d/whitelist-domains.conf"
DOMLOGS="/usr/local/apache/domlogs"
OUTPUT="/etc/fail2ban/jail.d/99-domlog-logpath.conf"

[ "$EUID" -eq 0 ] || { echo "Run as root"; exit 1; }

excluded_users=""
excluded_domains=""
if [ -f "$CONFIG" ] && [ -r "$CONFIG" ]; then
   excluded_users=$(grep -E '^EXCLUDED_USERS=' "$CONFIG" | cut -d= -f2- | tr ',' ' ')
   excluded_domains=$(grep -E '^EXCLUDED_DOMAINS=' "$CONFIG" | cut -d= -f2- | tr ',' ' ')
   excluded_users=$(echo "$excluded_users" | xargs)
   excluded_domains=$(echo "$excluded_domains" | xargs)
fi

paths=""
if [ ! -d "$DOMLOGS" ]; then
   paths="/usr/local/apache/domlogs/*/*"
elif [ -z "$excluded_users" ] && [ -z "$excluded_domains" ]; then
   # No exclusions: use wildcard (simpler, no huge config)
   paths="/usr/local/apache/domlogs/*/*"
else
   while IFS= read -r -d '' f; do
      [ -f "$f" ] || continue
      user=$(basename "$(dirname "$f")")
      domain=$(basename "$f")

      # Check excluded user
      if [ -n "$excluded_users" ]; then
         for u in $excluded_users; do
            [ "$u" = "$user" ] && continue 2
         done
      fi

      # Check excluded domain (match domain or domain-ssl_log etc)
      if [ -n "$excluded_domains" ]; then
         for d in $excluded_domains; do
            case "$domain" in
               "$d"|"$d"-*) continue 2 ;;
            esac
         done
      fi

      paths="$paths $f"
   done < <(find "$DOMLOGS" -mindepth 2 -maxdepth 2 -type f -print0 2>/dev/null || true)

   paths=$(echo "$paths" | xargs)
   if [ -z "$paths" ]; then
      paths="/usr/local/apache/domlogs/*/*"
   fi
fi

mkdir -p "$(dirname "$OUTPUT")"
cat > "$OUTPUT" << EOF
# Auto-generated by generate-logpath.sh - do not edit
# Excludes: EXCLUDED_USERS, EXCLUDED_DOMAINS from /etc/fail2ban/conf.d/whitelist-domains.conf

[apache-high-volume]
logpath = $paths

[wordpress-wp-login]
logpath = $paths
EOF

echo "Generated $OUTPUT"
