#!/bin/bash
# Generate fail2ban filters and jails for User-Agent keyword blocking
# Reads: /etc/fail2ban/scripts/useragent-keywords.conf
# Format per line: keyword|maxretry|findtime|bantime (pipe-separated)
# Example: python|1|60|3600

CONFIG="/etc/fail2ban/scripts/useragent-keywords.conf"
FILTER_DIR="/etc/fail2ban/filter.d"
JAIL_DIR="/etc/fail2ban/jail.d"
LOGPATH="/usr/local/apache/domlogs/*/*"

[ ! -f "$CONFIG" ] && {
    rm -f "${JAIL_DIR}"/apache-ua-*.conf 2>/dev/null
    fail2ban-client reload 2>/dev/null || true
    exit 0
}

# Escape keyword for use in regex (safe for fail2ban)
escape_regex() {
    echo "$1" | sed 's/[.[\*^$()+?{|\\]/\\&/g'
}

mkdir -p "$FILTER_DIR" "$JAIL_DIR"
CREATED_JAILS=""

while IFS='|' read -r keyword maxretry findtime bantime _; do
    [ -z "$keyword" ] && continue
    keyword=$(echo "$keyword" | tr -d ' ')
    [ -z "$keyword" ] && continue
    maxretry=$(echo "${maxretry:-1}" | tr -cd '0-9')
    findtime=$(echo "${findtime:-60}" | tr -cd '0-9')
    bantime=$(echo "${bantime:-3600}" | tr -cd '0-9')
    [ -z "$maxretry" ] && maxretry=1
    [ -z "$findtime" ] && findtime=60
    [ -z "$bantime" ] && bantime=3600
    maxretry=$((maxretry > 0 ? maxretry : 1))
    findtime=$((findtime > 0 ? findtime : 60))
    bantime=$((bantime > 0 ? bantime : 3600))

    # Special case: _empty_ = block requests with missing/empty User-Agent
    if [ "$keyword" = "_empty_" ]; then
        jail_id="empty"
        # Apache combined: match when user-agent (last "..") is "-"
        failregex="^<HOST> - .* \".*\" [0-9]+ [0-9]+ \".*\" \"-\"$"
        filter_comment="Blocks requests with missing/empty User-Agent"
    else
        jail_id=$(echo "$keyword" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/^-*//;s/-*$//')
        [ -z "$jail_id" ] && jail_id="kw"
        kw_esc=$(escape_regex "$keyword")
        failregex="^<HOST> - .* \".*\" [0-9]+ [0-9]+ \".*\" \"(?i).*${kw_esc}.*\""
        filter_comment="Blocks requests where User-Agent contains \"$keyword\" (case-insensitive)"
    fi
    jail_name="apache-ua-${jail_id}"
    filter_file="${FILTER_DIR}/${jail_name}.conf"

    cat > "$filter_file" << EOF
# Fail2Ban filter: $filter_comment
# Generated by update-useragent-jails.sh

[Definition]
failregex = $failregex
ignoreregex =
# Apache combined log timestamp [dd/Mon/YYYY:HH:MM:SS +zzzz]
datepattern = ^[^\\[]*\\[({DATE})
              {^LN-BEG}
EOF

    cat > "${JAIL_DIR}/${jail_name}.conf" << EOF
# User-Agent keyword: $keyword (generated by update-useragent-jails.sh)
[${jail_name}]
enabled = true
port = http,https
filter = ${jail_name}
backend = polling
logpath = ${LOGPATH}
maxretry = ${maxretry}
findtime = ${findtime}
bantime = ${bantime}
banaction = csf-domain
banaction_allports = csf-domain
EOF
    CREATED_JAILS="${CREATED_JAILS} ${jail_name}"
done < <(grep -v '^#' "$CONFIG" | grep -v '^[[:space:]]*$')

# Remove filter and jail configs no longer in use
for old in "$FILTER_DIR"/apache-ua-*.conf "${JAIL_DIR}"/apache-ua-*.conf; do
    [ -f "$old" ] || continue
    base=$(basename "$old" .conf)
    echo "$CREATED_JAILS" | grep -qwF "$base" || rm -f "$old"
done

# Reload fail2ban
fail2ban-client reload 2>/dev/null || true
